name: Update Snake

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Update Snake
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: liukenmonteiro
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake"
          git push origin main
